# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # Pick your own package manager and build script
      - run: deno run --allow-net --allow-read --allow-write fetch.ts
      - run: rm -rf dist && mkdir dist
      - run: cp CNAME index.html skills.json farming.json ./dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Commit report
        run: |
          git add .
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'tonymannino@me.com'
          git commit -am "CI Commit"
          git push
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4